App\Domain\Entity\User:
    type: entity
    repositoryClass: App\Infrastructure\Repository\UserRepository
    id:
        id:
            type: uuid
            generator:
                strategy: NONE
    fields:
        name:
            type: string
            length: 255
            nullable: false
        email:
            type: string
            length: 255
            unique: true
            nullable: false
        phone:
            type: bigint
            length:
            nullable: true
            options:
                unsigned: true
